### ISSUE TITLE
Confusion in Nginx, #414

### ISSUE THREAD

**Issue by piotrkot** [yegor256/thindeck#458]
Todo #345 demands handling `*.main.config` files but as an example gives `"www.example.com.hosts.conf"`. I think I think should be `"www.example.com.main.conf"`, instead. Please, fix it.

Next, the method `updateConfigScript` updates `*.hosts.config` files representing Load Balancing Group. I think it should rather be called `updateLoadBalancingGroupScript` or similar. Please, fix it.

Then the Todo #345 becomes clear that requires creation of a method `updateServerConfigScript` which should handle `*.main.config` files.

Please, correct me if I am wrong.

**Comment by davvd** [comment]
@wb14123 please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have; **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@rultor only @piotrkot can close this issue, since he opened it

**Comment by wb14123** [comment]
@piotrkot check it pls.

**Comment by piotrkot** [comment]
@wb14123 It's fine. Thanks.

**Comment by davvd** [comment]
@wb14123 **30 mins** added to your account (payment number `AP-88Y50285CC4305808`), many thanks for your contribution!; +30 to your rating, your total score is +45
